# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='geolocation_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
